/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.WareHouseManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PHSenterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.PHSorganization;
import Business.WorkQueue.BuyNewMedicalDeviceRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nirav gupta
 */
public class RequestDeviceBuyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestDeviceBuyJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    Organization organization;
    EcoSystem system;
    
    public RequestDeviceBuyJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.enterprise=enterprise;
        this.organization=organization;
        populateDeviceBuyRequestsTable();
    }

    
    public void populateDeviceBuyRequestsTable(){
            DefaultTableModel model = (DefaultTableModel) requestjTable1.getModel();
            model.setRowCount(0);
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof PHSenterprise) {
                    for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                        if (o instanceof PHSorganization) {
                            for (WorkRequest request : o.getWorkQueue().getWorkRequestList()) {
                                if (request instanceof BuyNewMedicalDeviceRequest) {
                                    Object[] row = new Object[5];
                                    row[0] = request;
                                    row[1] = request.getRequestDate();
                                    row[2] = ((BuyNewMedicalDeviceRequest) request).getRequiredMedicalDeviceType();
                                    row[3] = ((BuyNewMedicalDeviceRequest) request).getLocationRequired();
                                    row[4] = request.getStatus();
                                    model.addRow(row);
                                }
                            }
                        }
                    }
                }
            }
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestjTable1 = new javax.swing.JTable();
        backjButton4 = new javax.swing.JButton();
        closejButton1 = new javax.swing.JButton();

        jLabel1.setText("NEW DEVICE BUY REQUEST ");

        requestjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Date", "Device Type  Required", "Location Required", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestjTable1);

        backjButton4.setText("<<Back");
        backjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton4ActionPerformed(evt);
            }
        });

        closejButton1.setBackground(new java.awt.Color(0, 0, 0));
        closejButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        closejButton1.setText("Close Request");
        closejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closejButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(backjButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backjButton4)
                    .addComponent(closejButton1))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton4ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton4ActionPerformed

    private void closejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closejButton1ActionPerformed
       int selectedRequest = requestjTable1.getSelectedRow();
        
        if (selectedRequest < 0 ){
            JOptionPane.showMessageDialog(null, "Please select a request from request table");
            return;
        }
        
        WorkRequest request = (WorkRequest)requestjTable1.getValueAt(selectedRequest, 0);
        
        if (!request.getStatus().equalsIgnoreCase(("Resolved"))){
            JOptionPane.showMessageDialog(null, "Request is not resolved yet !!");
            return;
        }
        
        int reply = JOptionPane.showConfirmDialog(null,"CLOSE DEVICE BUY REQUEST ?", "CLOSE REQUEST", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION){
                request.setStatus("CLOSED");
                request.setMessage("CLOSED");
            }else{
                return;
            }
            
            populateDeviceBuyRequestsTable();
    }//GEN-LAST:event_closejButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton4;
    private javax.swing.JButton closejButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable requestjTable1;
    // End of variables declaration//GEN-END:variables
}
