/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PHSlManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author nirav gupta
 */
public class PHSlManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PHSlManagerWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    UserAccount account; 
    Enterprise enterprise; 
    EcoSystem system;
    Organization organization;
    
    public PHSlManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Organization organization, EcoSystem system) {
        initComponents();
        this.enterprise=enterprise;
        this.account=account;
        this.system=system;
        this.organization=organization;
        this.userProcessContainer=userProcessContainer;
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageDeviceBuyRequestsjButton1 = new javax.swing.JButton();
        manageFundsjButton2 = new javax.swing.JButton();
        manageSupplierApprovalsjButton2 = new javax.swing.JButton();
        buyMedicalDevicejButton2 = new javax.swing.JButton();
        viewOrderHistoryjButton1 = new javax.swing.JButton();
        viewDevicePerformancejButton2 = new javax.swing.JButton();

        jLabel1.setText("PHS MANAGER WORK AREA");

        manageDeviceBuyRequestsjButton1.setBackground(new java.awt.Color(0, 153, 153));
        manageDeviceBuyRequestsjButton1.setText("Manage Device Buy Requests");
        manageDeviceBuyRequestsjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDeviceBuyRequestsjButton1ActionPerformed(evt);
            }
        });

        manageFundsjButton2.setBackground(new java.awt.Color(0, 153, 153));
        manageFundsjButton2.setText("Manage Funds");
        manageFundsjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFundsjButton2ActionPerformed(evt);
            }
        });

        manageSupplierApprovalsjButton2.setBackground(new java.awt.Color(0, 153, 153));
        manageSupplierApprovalsjButton2.setText("Manage Supplier Approvals");
        manageSupplierApprovalsjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSupplierApprovalsjButton2ActionPerformed(evt);
            }
        });

        buyMedicalDevicejButton2.setBackground(new java.awt.Color(0, 153, 153));
        buyMedicalDevicejButton2.setText("Buy New Medical Device");
        buyMedicalDevicejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyMedicalDevicejButton2ActionPerformed(evt);
            }
        });

        viewOrderHistoryjButton1.setBackground(new java.awt.Color(0, 153, 153));
        viewOrderHistoryjButton1.setText("View Order History");
        viewOrderHistoryjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderHistoryjButton1ActionPerformed(evt);
            }
        });

        viewDevicePerformancejButton2.setBackground(new java.awt.Color(0, 153, 153));
        viewDevicePerformancejButton2.setText("View Device Performance");
        viewDevicePerformancejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDevicePerformancejButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewDevicePerformancejButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(manageDeviceBuyRequestsjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addComponent(manageSupplierApprovalsjButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(manageFundsjButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buyMedicalDevicejButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewOrderHistoryjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(manageDeviceBuyRequestsjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(manageFundsjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(manageSupplierApprovalsjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(buyMedicalDevicejButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(viewOrderHistoryjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(viewDevicePerformancejButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageSupplierApprovalsjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSupplierApprovalsjButton2ActionPerformed
        ManageSupplierApprovalsJPanel h1 = new ManageSupplierApprovalsJPanel(userProcessContainer,enterprise,organization, system);
        userProcessContainer.add("h1", h1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageSupplierApprovalsjButton2ActionPerformed

    private void manageFundsjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFundsjButton2ActionPerformed
        ManageFundsJPanel h2 = new ManageFundsJPanel(userProcessContainer,enterprise,organization, system);
        userProcessContainer.add("h2", h2);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageFundsjButton2ActionPerformed

    private void manageDeviceBuyRequestsjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDeviceBuyRequestsjButton1ActionPerformed
        ManageBuyDeviceRequestsJPanel h3 = new ManageBuyDeviceRequestsJPanel(userProcessContainer,enterprise,organization, system);
        userProcessContainer.add("h3", h3);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDeviceBuyRequestsjButton1ActionPerformed

    private void buyMedicalDevicejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyMedicalDevicejButton2ActionPerformed
        BuyMedicalDeviceJPanel h4 = new BuyMedicalDeviceJPanel(userProcessContainer,enterprise,organization, system);
        userProcessContainer.add("h4", h4);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_buyMedicalDevicejButton2ActionPerformed

    private void viewOrderHistoryjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderHistoryjButton1ActionPerformed
        ViewOrdersJPanel h5 = new ViewOrdersJPanel(userProcessContainer,enterprise,organization, system);
        userProcessContainer.add("h5", h5);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewOrderHistoryjButton1ActionPerformed

    private void viewDevicePerformancejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDevicePerformancejButton2ActionPerformed
        DevicePerformanceJPanel h6 = new DevicePerformanceJPanel(userProcessContainer,enterprise,organization, system);
        userProcessContainer.add("h6", h6);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewDevicePerformancejButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyMedicalDevicejButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageDeviceBuyRequestsjButton1;
    private javax.swing.JButton manageFundsjButton2;
    private javax.swing.JButton manageSupplierApprovalsjButton2;
    private javax.swing.JButton viewDevicePerformancejButton2;
    private javax.swing.JButton viewOrderHistoryjButton1;
    // End of variables declaration//GEN-END:variables
}
