/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SupplierRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PHSenterprise;
import Business.Network.Network;
import Business.Organization.HospitalAdminOrganization;
import Business.Organization.Organization;
import Business.Organization.PHSorganization;
import Business.Supplier.Supplier;
import Business.WorkQueue.SupplierEnrollmentRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author nirav gupta
 */
public class SubmitEnrollmentRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Supplier supplier;
    EcoSystem system;
    /**
     * Creates new form ManageEnrollmentRequestJPanel
     */
    public SubmitEnrollmentRequestJPanel(JPanel userProcessContainer, Supplier supplier, EcoSystem system) {
        initComponents();
        
        this.supplier=supplier;
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        
        supplierNamejTextField1.setText(supplier.getSupplyName());
        enrollmentStatusjTextField1.setText(supplier.getEnrollmentStatus());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitEnrollmentRequestjButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        supplierNamejTextField1 = new javax.swing.JTextField();
        enrollmentRequestjTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enrollmentStatusjTextField1 = new javax.swing.JTextField();

        submitEnrollmentRequestjButton1.setText("SUBMIT ENROLLMENT REQUEST");
        submitEnrollmentRequestjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEnrollmentRequestjButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("SUBMIT ENROLLMENT REQUEST");

        backButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backButton1.setText("<< Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("WELCOME");

        supplierNamejTextField1.setEnabled(false);

        jLabel3.setText("MESSAGE");

        jLabel4.setText("ENROLLMENT STATUS :");

        enrollmentStatusjTextField1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(supplierNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(enrollmentRequestjTextField1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(enrollmentStatusjTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))))
                            .addComponent(submitEnrollmentRequestjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton1)
                                .addGap(44, 44, 44)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(supplierNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(enrollmentStatusjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrollmentRequestjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(submitEnrollmentRequestjButton1)
                .addGap(42, 42, 42)
                .addComponent(backButton1)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton1ActionPerformed

    private void submitEnrollmentRequestjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEnrollmentRequestjButton1ActionPerformed

        String message = enrollmentRequestjTextField1.getText();
        
        if(enrollmentRequestjTextField1.getText().isEmpty()==true || enrollmentRequestjTextField1.getText().startsWith(" ")) {
            JOptionPane.showMessageDialog(null, "Please enter valid text in Message field");
            return;
        }
        
        if (supplier.getEnrollmentStatus().equalsIgnoreCase(Supplier.enrollmentStatusType.ENROLLED.getValue())){
            JOptionPane.showMessageDialog(null, "You are already enrolled");
            return;
        }
        
        SupplierEnrollmentRequest request = new SupplierEnrollmentRequest();
        
        request.setMessage(message);
        
        request.setSender(supplier);
        request.setStatus(Supplier.enrollmentStatusType.SENT.getValue());
        Date date = new Date();
        request.setRequestDate(date);
        request.setSupplier(supplier);

        
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof PHSenterprise) {
                    for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                        if (o instanceof PHSorganization) {
                            o.getWorkQueue().getWorkRequestList().add(request);
                            System.out.println("inside if");
                            supplier.getWorkQueue().getWorkRequestList().add(request);
                            JOptionPane.showMessageDialog(null,"Enrollment Request Created");
                            break;
                            
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_submitEnrollmentRequestjButton1ActionPerformed


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton1;
    private javax.swing.JTextField enrollmentRequestjTextField1;
    private javax.swing.JTextField enrollmentStatusjTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton submitEnrollmentRequestjButton1;
    private javax.swing.JTextField supplierNamejTextField1;
    // End of variables declaration//GEN-END:variables
}
