/*
 * ProductManagerWorkAreaJPanel.java
 *
 * Created on October 3, 2008, 8:06 AM
 */
package UserInterface.SupplierRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.Supplier.Supplier;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rushabh
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Supplier supplier;
    EcoSystem system;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    
    /** Creates new form ProductManagerWorkAreaJPanel */
    public SupplierWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Organization organization, EcoSystem System) {

        initComponents();
       this.userProcessContainer = userProcessContainer;
       this.system=System;
       this.userAccount=account;
       this.enterprise=enterprise;
       this.organization=organization;
       
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getEnterpriseType().getValue().equalsIgnoreCase("Supplier")) {
                    for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                        if (o.getName().equalsIgnoreCase("Supplier Organization")) {
                            SupplierOrganization suppOrg = (SupplierOrganization) o;
                            for (Supplier supp : suppOrg.getSupplierDirectory().getSupplierDict()) {
                                if (supp.getUsername().equalsIgnoreCase(userAccount.getUsername())) {
                                    supplier = supp;
                                    //supplier = b.getSupplierDirectory().searchSupplier(p.getFirstName());
                                }
                            }
                        }
                    }
                }
            }
        }
       
        
        
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        managePButton = new javax.swing.JButton();
        submitEnrollmentRequestButton1 = new javax.swing.JButton();
        manageMaintenanceButton2 = new javax.swing.JButton();
        viewOrdersAndInvoicesButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area (Product Manager Role)");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        managePButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        managePButton.setText("Manage Product Catalog >>");
        managePButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePButtonActionPerformed(evt);
            }
        });
        add(managePButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 290, 60));

        submitEnrollmentRequestButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitEnrollmentRequestButton1.setText("Submit Enrollment Request >>");
        submitEnrollmentRequestButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEnrollmentRequestButton1ActionPerformed(evt);
            }
        });
        add(submitEnrollmentRequestButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 290, 50));

        manageMaintenanceButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageMaintenanceButton2.setText("Manage Maintenance >>");
        manageMaintenanceButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMaintenanceButton2ActionPerformed(evt);
            }
        });
        add(manageMaintenanceButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 290, 50));

        viewOrdersAndInvoicesButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewOrdersAndInvoicesButton2.setText("View Orders and Invoices >>");
        viewOrdersAndInvoicesButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersAndInvoicesButton2ActionPerformed(evt);
            }
        });
        add(viewOrdersAndInvoicesButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 290, 50));
    }// </editor-fold>//GEN-END:initComponents
    private void managePButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePButtonActionPerformed
        // TODO add your handling code here:
       ManageProductCatalogJPanel j1 = new ManageProductCatalogJPanel(userProcessContainer, supplier);
        userProcessContainer.add("j1",j1);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePButtonActionPerformed

    private void submitEnrollmentRequestButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEnrollmentRequestButton1ActionPerformed
        SubmitEnrollmentRequestJPanel j2 = new SubmitEnrollmentRequestJPanel(userProcessContainer, supplier, system);
        userProcessContainer.add("j2",j2);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_submitEnrollmentRequestButton1ActionPerformed

    private void manageMaintenanceButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMaintenanceButton2ActionPerformed
        ManageDeviceMaintainenceJPanel j3 = new ManageDeviceMaintainenceJPanel(userProcessContainer, supplier,enterprise,organization, system);
        userProcessContainer.add("j3",j3);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageMaintenanceButton2ActionPerformed

    private void viewOrdersAndInvoicesButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersAndInvoicesButton2ActionPerformed
        ViewOrdersInvoicesJPanel j4 = new ViewOrdersInvoicesJPanel(userProcessContainer, supplier,enterprise,organization, system);
        userProcessContainer.add("j4",j4);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewOrdersAndInvoicesButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageMaintenanceButton2;
    private javax.swing.JButton managePButton;
    private javax.swing.JButton submitEnrollmentRequestButton1;
    private javax.swing.JButton viewOrdersAndInvoicesButton2;
    // End of variables declaration//GEN-END:variables
}
