/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SupplierRole;

import Business.Supplier.MedicalDevice;
import Business.Supplier.Supplier;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nirav gupta
 */
public class updateDeviceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form updateDeviceJPanel
     */
    Supplier supplier;
    JPanel userProcessContainer;
    MedicalDevice device;
    
    public updateDeviceJPanel(JPanel userProcessContainer, Supplier supplier, MedicalDevice device) {
        initComponents();
        
        this.supplier = supplier;
        this.userProcessContainer = userProcessContainer;
        this.device = device;
        
        modelNoField3.setEnabled(false);
        idField.setEnabled(false);
        deviceNameField2.setEnabled(false);
        deviceTypeField1.setEnabled(false);
        priceField1.setEnabled(false);
        availabilityField1.setEnabled(false);
        nextMaintainencejDateChooser1.setEnabled(false);
        manufacturejDateChooser1.setEnabled(false);
        warrantyExpDatejDateChooser1.setEnabled(false);
        SAVEButton1.setEnabled(false);
       
        deviceNameField2.setText(device.getDeviceName());
        modelNoField3.setText(String.valueOf(device.getModelNumber()));
        deviceTypeField1.setText(device.getDeviceType());
        idField.setText(String.valueOf(device.getDeviceID()));
        priceField1.setText(String.valueOf(device.getPurchaseCost()));
        availabilityField1.setText(String.valueOf(device.getAvailability()));
        nextMaintainencejDateChooser1.setDate(device.getNextMaitainenceDueDate());
        manufacturejDateChooser1.setDate(device.getManufactureDate());
        warrantyExpDatejDateChooser1.setDate(device.getWarrantyExpirationDate());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        availabilityjLabel3 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        deviceTypeField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        priceField1 = new javax.swing.JTextField();
        availabilityField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nextMaintainencejDateChooser1 = new com.toedter.calendar.JDateChooser();
        manufacturejDateChooser1 = new com.toedter.calendar.JDateChooser();
        warrantyExpDatejDateChooser1 = new com.toedter.calendar.JDateChooser();
        deviceNameField2 = new javax.swing.JTextField();
        modelNoField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SAVEButton1 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Product ID:");

        idField.setEditable(false);
        idField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        availabilityjLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        availabilityjLabel3.setText("Availability:");

        updateButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateButton.setText("update Product");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        backButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton1.setText("<< Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Device Type:");

        deviceTypeField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Product Price:");

        priceField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        availabilityField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Warranty Exp Date:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Next Maintainence Date:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Manufacture Date:");

        deviceNameField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        modelNoField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Device Name:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Model No:");

        jLabel1.setText("UPDATE PRODUCT");

        SAVEButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SAVEButton1.setText("Save");
        SAVEButton1.setEnabled(false);
        SAVEButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel8)
                                .addGap(32, 32, 32)
                                .addComponent(deviceNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel9)
                                .addGap(29, 29, 29)
                                .addComponent(modelNoField3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addComponent(deviceTypeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(priceField1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(availabilityjLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(availabilityField1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(nextMaintainencejDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel6)
                                .addGap(25, 25, 25)
                                .addComponent(manufacturejDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(warrantyExpDatejDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(backButton1)
                                .addGap(74, 74, 74)
                                .addComponent(SAVEButton1)
                                .addGap(32, 32, 32)
                                .addComponent(updateButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel1)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deviceNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelNoField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deviceTypeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(availabilityjLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availabilityField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextMaintainencejDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturejDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warrantyExpDatejDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateButton)
                        .addComponent(SAVEButton1)))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed

         deviceNameField2.setEnabled(true);
       deviceTypeField1.setEnabled(true);
       priceField1.setEnabled(true);
       availabilityField1.setEnabled(true);
       nextMaintainencejDateChooser1.setEnabled(true);
       manufacturejDateChooser1.setEnabled(true);
       warrantyExpDatejDateChooser1.setEnabled(true);
       SAVEButton1.setEnabled(true);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton1ActionPerformed

    private void SAVEButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEButton1ActionPerformed
       if(deviceNameField2.getText().isEmpty()==true || deviceNameField2.getText().startsWith(" ")) {
            JOptionPane.showMessageDialog(null, "Please enter valid text in Device Name field");
            return;
        }

        if(deviceTypeField1.getText().isEmpty()==true || deviceTypeField1.getText().startsWith(" ")) {
            JOptionPane.showMessageDialog(null, "Please enter valid text in Device Type field");
            return;
        }
        if(priceField1.getText().isEmpty()==true || priceField1.getText().startsWith(" ")) {
            JOptionPane.showMessageDialog(null, "Please enter valid text in Price field");
            return;
        }

        if(availabilityField1.getText().isEmpty()==true || availabilityField1.getText().startsWith(" ")) {
            JOptionPane.showMessageDialog(null, "Please enter valid text in Availability field");
            return;
        }
        
        try {
            int price = Integer.parseInt(priceField1.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                "Error: Please enter integer values in price field");
            return;
        }

        try {
            int availability = Integer.parseInt(availabilityField1.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                "Error: Please enter integer values in availabilty field");
            return;
        }

        Date date = new Date();

        if (manufacturejDateChooser1.getDate().after(date)){
            JOptionPane.showMessageDialog(null, "Please choose Manufacture date BEFORE Current Date");
            return;
        }

        if (nextMaintainencejDateChooser1.getDate().before(date)){
            JOptionPane.showMessageDialog(null, "Please choose Next Maintainence date AFTER Current Date");
            return;
        }

        if (warrantyExpDatejDateChooser1.getDate().before(date)){
            JOptionPane.showMessageDialog(null, "Please choose Warranty Expiration date AFTER Current Date");
            return;
        }

        
        int update = JOptionPane.showConfirmDialog(null, "Are you sure to update?", "Confirm Update", JOptionPane.YES_NO_OPTION);
        if(update == JOptionPane.YES_OPTION) {

        for(MedicalDevice md : supplier.getMedicalDeviceCatalog().getProductCatalog()) {
            if(md.getDeviceName().equalsIgnoreCase(device.getDeviceName())) {
                md.setDeviceName(deviceNameField2.getText());
                md.setDeviceType(deviceTypeField1.getText());
                md.setPurchaseCost(Integer.parseInt(priceField1.getText()));
                md.setAvailability(Integer.parseInt(availabilityField1.getText()));
                md.setNextMaitainenceDueDate(nextMaintainencejDateChooser1.getDate());
                md.setManufactureDate(manufacturejDateChooser1.getDate());
                md.setWarrantyExpirationDate(warrantyExpDatejDateChooser1.getDate());
            }  
        }
           JOptionPane.showMessageDialog(null, "Device updated");
        
        }
        else {
            return;
        }
        
    }//GEN-LAST:event_SAVEButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SAVEButton1;
    private javax.swing.JTextField availabilityField1;
    private javax.swing.JLabel availabilityjLabel3;
    private javax.swing.JButton backButton1;
    private javax.swing.JTextField deviceNameField2;
    private javax.swing.JTextField deviceTypeField1;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser manufacturejDateChooser1;
    private javax.swing.JTextField modelNoField3;
    private com.toedter.calendar.JDateChooser nextMaintainencejDateChooser1;
    private javax.swing.JTextField priceField1;
    private javax.swing.JButton updateButton;
    private com.toedter.calendar.JDateChooser warrantyExpDatejDateChooser1;
    // End of variables declaration//GEN-END:variables
}
