/*
 * CreateProductJPanel.java
 *
 * Created on September 18, 2008, 2:54 PM
 */
package UserInterface.SupplierRole;


import Business.Supplier.MedicalDevice;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rushabh
 */
public class ViewProductDetailJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    
    MedicalDevice medicalDevice;
    
    
    /** Creates new form CreateProductJPanel */
    public ViewProductDetailJPanel(JPanel upc, MedicalDevice md) {
        initComponents();
        userProcessContainer = upc;
        this.medicalDevice=md;
        
        nameField.setText(medicalDevice.getDeviceName());
        idField.setText((String.valueOf(md.getDeviceID())));
        priceField1.setText(String.valueOf(md.getPurchaseCost()));
        availabilityField2.setText(String.valueOf(md.getAvailability()));
        nextMaintainenceField3.setText(String.valueOf(md.getNextMaitainenceDueDate()));
        manufactureDateField.setText(String.valueOf(md.getManufactureDate()));
        
    }

    
    public static String convertInteger(int i) {
        return Integer.toString(i);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        manufactureDateField = new javax.swing.JTextField();
        backButton1 = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        priceField1 = new javax.swing.JTextField();
        availabilityField2 = new javax.swing.JTextField();
        nextMaintainenceField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("View Product Detail");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 25, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Device Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, 30));

        nameField.setEditable(false);
        nameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 159, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Manufacture Date:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, 30));

        manufactureDateField.setEditable(false);
        manufactureDateField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manufactureDateField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(manufactureDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 159, -1));

        backButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton1.setText("<< Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        idField.setEditable(false);
        idField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 159, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Device ID:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 30));

        priceField1.setEditable(false);
        priceField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        priceField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(priceField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 159, -1));

        availabilityField2.setEditable(false);
        availabilityField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        availabilityField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(availabilityField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 159, -1));

        nextMaintainenceField3.setEditable(false);
        nextMaintainenceField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nextMaintainenceField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(nextMaintainenceField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 159, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Device Price:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Device Availability:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Next Maintainence:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton1ActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availabilityField2;
    private javax.swing.JButton backButton1;
    private javax.swing.JTextField idField;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField manufactureDateField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nextMaintainenceField3;
    private javax.swing.JTextField priceField1;
    // End of variables declaration//GEN-END:variables
}
