/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.CareTeamMemberRole;

import Business.CareTeam.CareTeamMember;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.CareTeamOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author nirav gupta
 */
public class CareTeamMemberWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CareTeamMemberWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount account;
    
    public CareTeamMemberWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system; 
        this.account=account;
        
    }

    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        updateProfilejButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("CARE TEAM MEMBER WORK AREA");

        updateProfilejButton1.setText("Update Profile >>");
        updateProfilejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfilejButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(updateProfilejButton1)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(updateProfilejButton1)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateProfilejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfilejButton1ActionPerformed
        
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof HospitalEnterprise) {
                    for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                        if (org instanceof CareTeamOrganization){
                            CareTeamOrganization ctOrg = (CareTeamOrganization) org;
                            for (CareTeamMember ctm : ctOrg.getCareTeamDirectory().getCareTeamMemberList()) {
                                if (ctm.getUsername().equalsIgnoreCase(account.getUsername())){
                                        UpdateProfileJPanel b1 = new UpdateProfileJPanel(userProcessContainer, ctm , e, system);
                                        userProcessContainer.add("b1",b1);
                                        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                                        layout.next(userProcessContainer);
                                }
                            }
                        }
                    }
                }
            }
        }
        
        
    }//GEN-LAST:event_updateProfilejButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton updateProfilejButton1;
    // End of variables declaration//GEN-END:variables
}
