/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.OperatingRoomManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.OperatingRoom.OperatingRoom;
import Business.Organization.OperatingRoomOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nirav gupta
 */
public class AddOperatingRoomsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddOperatinRoomsJPanel
     */
    JPanel userProcessContainer;
    UserAccount account; 
    EcoSystem system;
    Enterprise enterprise;
    
    public AddOperatingRoomsJPanel(JPanel userProcessContainer, UserAccount account,Enterprise enterprise, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.system=system;
        this.enterprise=enterprise;
        

        isOccupiedjComboBox1.removeAllItems();
        hospitalNamejTextField1.setText(enterprise.getName());
      for(OperatingRoom.bookedStatusType type : OperatingRoom.bookedStatusType.values()){
            isOccupiedjComboBox1.addItem(type);
        }
        
    }

    

   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        roomNamejTextField1 = new javax.swing.JTextField();
        roomNojTextField1 = new javax.swing.JTextField();
        addOperatingRoomjButton1 = new javax.swing.JButton();
        hospitalNamejTextField1 = new javax.swing.JTextField();
        isOccupiedjComboBox1 = new javax.swing.JComboBox();
        backJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ADD OPERATING ROOMS");

        jLabel2.setText("Room Name:");

        jLabel3.setText("Room No:");

        jLabel4.setText("Hospital:");

        jLabel5.setText("Is Occupied Status:");

        addOperatingRoomjButton1.setText("Add Operating Room");
        addOperatingRoomjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOperatingRoomjButton1ActionPerformed(evt);
            }
        });

        hospitalNamejTextField1.setEnabled(false);

        isOccupiedjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roomNamejTextField1)
                            .addComponent(roomNojTextField1)
                            .addComponent(hospitalNamejTextField1)
                            .addComponent(isOccupiedjComboBox1, 0, 89, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(backJButton)
                        .addGap(105, 105, 105)
                        .addComponent(addOperatingRoomjButton1)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(roomNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(roomNojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hospitalNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(isOccupiedjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addOperatingRoomjButton1)
                    .addComponent(backJButton))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addOperatingRoomjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOperatingRoomjButton1ActionPerformed

        if(roomNamejTextField1.getText().isEmpty()==true || roomNamejTextField1.getText().startsWith(" ")) {
            JOptionPane.showMessageDialog(null, "Please enter valid text in Room Name field");
            return;
        }
        
        if(roomNojTextField1.getText().isEmpty()==true || roomNojTextField1.getText().startsWith(" ")) {
            JOptionPane.showMessageDialog(null, "Please enter valid text in Room No field");
            return;
        }
        
        try {
            int roomNo = Integer.parseInt(roomNojTextField1.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                "Error: Please enter integer values in room No field");
            return;
        }
        
        String bookedStatus = String.valueOf(isOccupiedjComboBox1.getSelectedItem());
        
        for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (o instanceof OperatingRoomOrganization) {
                OperatingRoomOrganization opro = (OperatingRoomOrganization) o;
                for (OperatingRoom or : opro.getOperatingRoomList()) {
                    if (or.getRoomName().equalsIgnoreCase(roomNamejTextField1.getText())) {
                        JOptionPane.showMessageDialog(null, "Room name already exists. Please enter different name");
                        return;
                    } else if (or.getRoomNo() == Integer.parseInt(roomNojTextField1.getText())) {
                        JOptionPane.showMessageDialog(null, "Room no already exists. Please enter different no");
                        return;
                    }
                }
            }
        }
        
                    for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
                        if (o instanceof OperatingRoomOrganization){  
                            OperatingRoomOrganization opro = (OperatingRoomOrganization) o;
                            OperatingRoom orm = opro.addOperatingRoominDir();
                            orm.setHospitalName(enterprise.getName());
                            orm.setRoomName(roomNamejTextField1.getText());
                            orm.setRoomNo(Integer.valueOf(roomNojTextField1.getText()));
                            orm.setBookedStatus(bookedStatus);
                            JOptionPane.showMessageDialog(null, "Operating romm added");
                        }
                    }

    }//GEN-LAST:event_addOperatingRoomjButton1ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOperatingRoomjButton1;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField hospitalNamejTextField1;
    private javax.swing.JComboBox isOccupiedjComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField roomNamejTextField1;
    private javax.swing.JTextField roomNojTextField1;
    // End of variables declaration//GEN-END:variables
}
