/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Schedule.DeviceBookingHistory;
import Business.Supplier.MedicalDevice;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SurgeryOperationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nirav gupta
 */
public class ReportFailureJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportFailureJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise; 
    Organization organization; 
    UserAccount account; 
    EcoSystem system;
    MedicalDevice md;
    WorkRequest request;
    
    public ReportFailureJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount account, EcoSystem system, MedicalDevice medicalDevice, WorkRequest request) {
        initComponents();
        this.enterprise=enterprise;
        this.organization=organization;
        this.system=system;
        this.account=account;
        this.userProcessContainer=userProcessContainer;
        this.md=medicalDevice;
        this.request=request;
        
        deviceNameField.setText(md.getDeviceName());
        deviceTypeField.setText(md.getDeviceType());
        deviceMaufacturerField1.setText(md.getManufacturerName());
        previousFailureField2.setText(String.valueOf(md.getFailureCount()));
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deviceNameField = new javax.swing.JTextField();
        deviceTypeField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        deviceMaufacturerField1 = new javax.swing.JTextField();
        previousFailureField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        failureReasonField3 = new javax.swing.JTextField();
        reportDeviceFailurejButton1 = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("REPORT FAILURE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Device Name:");

        deviceNameField.setEditable(false);
        deviceNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deviceNameField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        deviceTypeField.setEditable(false);
        deviceTypeField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deviceTypeField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Device Type:");

        deviceMaufacturerField1.setEditable(false);
        deviceMaufacturerField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deviceMaufacturerField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        previousFailureField2.setEditable(false);
        previousFailureField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        previousFailureField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Device Manufacturer:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Device Previous Failure count:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Device Current failure reason:");

        failureReasonField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        failureReasonField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        reportDeviceFailurejButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reportDeviceFailurejButton1.setText("Report Device Failure");
        reportDeviceFailurejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportDeviceFailurejButton1ActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(reportDeviceFailurejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(277, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deviceNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(deviceTypeField)
                            .addComponent(deviceMaufacturerField1)
                            .addComponent(previousFailureField2)
                            .addComponent(failureReasonField3))))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deviceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deviceTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deviceMaufacturerField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previousFailureField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(failureReasonField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(reportDeviceFailurejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reportDeviceFailurejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportDeviceFailurejButton1ActionPerformed

        if(failureReasonField3.getText().isEmpty()==true || failureReasonField3.getText().startsWith(" ")) {
            JOptionPane.showMessageDialog(null, "Please enter valid text in failure reason field");
            return;
        }
       
        //md.addFailureInDeviceFailureList(failureReasonField3.getText());
        if (!(((SurgeryOperationWorkRequest) request).getAssignedMedicalDevice() == null)){
        for (DeviceBookingHistory dbh : md.getBookingHistorylist()){
            if (dbh.getPreviousScheduledBookingDate().equals(((SurgeryOperationWorkRequest) request).getOperationDate())){
                dbh.setFailureStatusReason(failureReasonField3.getText());
                dbh.setFailureStatusValue(true);
                dbh.setFailureFixedValue(false);
            }
        }
        
        
        
        int deviceFailCount = md.getFailureCount();
        deviceFailCount = deviceFailCount + 1;
        
        md.setFailureCount(deviceFailCount);
        
        JOptionPane.showMessageDialog(null, "Device failure Reported");
        reportDeviceFailurejButton1.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null, "No device Assigned to the request");
        }
    }//GEN-LAST:event_reportDeviceFailurejButton1ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField deviceMaufacturerField1;
    private javax.swing.JTextField deviceNameField;
    private javax.swing.JTextField deviceTypeField;
    private javax.swing.JTextField failureReasonField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField previousFailureField2;
    private javax.swing.JButton reportDeviceFailurejButton1;
    // End of variables declaration//GEN-END:variables
}
