/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.CareTeamLeaderRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author nirav gupta
 */
public class CareTeamLeaderWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CareTeamLeaderWorkAreaJPanel
     */
    JPanel userProcessContainer; EcoSystem system;UserAccount account;
    Enterprise enterprise; Organization organization;
    
    public CareTeamLeaderWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Organization organization, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.account=account;
        this.enterprise=enterprise;
        this.organization=organization;
    }

    


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageDoctorRequestsjButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        viewDeviceUsageTrendsjButton2 = new javax.swing.JButton();

        manageDoctorRequestsjButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        manageDoctorRequestsjButton2.setText(" MANAGE DOCTOR'S REQUESTS >>");
        manageDoctorRequestsjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDoctorRequestsjButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("CARE TEAM LEADER WORK AREA");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("MANAGE OPERATION CARE TEAM REQUESTS >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        viewDeviceUsageTrendsjButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewDeviceUsageTrendsjButton2.setText("VIEW DEVICE USAGE & TRENDS >>");
        viewDeviceUsageTrendsjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDeviceUsageTrendsjButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewDeviceUsageTrendsjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(manageDoctorRequestsjButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(92, 92, 92)
                .addComponent(manageDoctorRequestsjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(viewDeviceUsageTrendsjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageDoctorRequestsjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDoctorRequestsjButton2ActionPerformed
        ManageDoctorsRequestsJPanel a1 = new ManageDoctorsRequestsJPanel(userProcessContainer, account,enterprise,organization, system);
        userProcessContainer.add("a1",a1);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDoctorRequestsjButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManageOperationCareTeamRequestsJPanel a2 = new ManageOperationCareTeamRequestsJPanel(userProcessContainer, account,enterprise,organization, system);
        userProcessContainer.add("a2",a2);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewDeviceUsageTrendsjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDeviceUsageTrendsjButton2ActionPerformed
        ViewDeviceUsageTrendsJPanel a3 = new ViewDeviceUsageTrendsJPanel(userProcessContainer, account,enterprise,organization, system);
        userProcessContainer.add("a3",a3);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewDeviceUsageTrendsjButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageDoctorRequestsjButton2;
    private javax.swing.JButton viewDeviceUsageTrendsjButton2;
    // End of variables declaration//GEN-END:variables
}
