/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SystemAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Enterprise.WarehouseEnterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nirav gupta
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    JPanel userProcessContainer; EcoSystem system;
    
    public ManageEnterpriseJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        populateEnterpriseTable();
        populateComboBox();
        
    }

    public void populateEnterpriseTable(){
        
        DefaultTableModel dtm = (DefaultTableModel) enterprisejTable1.getModel();
        dtm.setRowCount(0);
        for (Network network : system.getNetworkList()){
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            Object[] row = new Object[3];
           row[0] = enterprise.getName();
           row[1] = network.getName();
           row[2] = enterprise.getEnterpriseType().getValue();
           dtm.addRow(row);
        }
        }
    }
    
    public void populateComboBox(){
        
        networkjComboBox1.removeAllItems();
        enterpriseTypejComboBox1.removeAllItems();
        
        for(Network network : system.getNetworkList()){
            networkjComboBox1.addItem(network);
        } 
        
        for(Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()){
            enterpriseTypejComboBox1.addItem(type);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterprisejTable1 = new javax.swing.JTable();
        networkjComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enterpriseTypejComboBox1 = new javax.swing.JComboBox();
        CREATEjButton1 = new javax.swing.JButton();
        enterprisenAMEjTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        backjButton2 = new javax.swing.JButton();

        enterprisejTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise", "Network", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterprisejTable1);
        if (enterprisejTable1.getColumnModel().getColumnCount() > 0) {
            enterprisejTable1.getColumnModel().getColumn(0).setResizable(false);
            enterprisejTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        networkjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkjComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("NETWORK");

        jLabel2.setText("ENTERPRISE TYPE");

        enterpriseTypejComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterpriseTypejComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseTypejComboBox1ActionPerformed(evt);
            }
        });

        CREATEjButton1.setText("CREATE");
        CREATEjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATEjButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("ENTERPRISE NAME");

        backjButton2.setText("<<Back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(networkjComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enterpriseTypejComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enterprisenAMEjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backjButton2)
                                .addGap(116, 116, 116)
                                .addComponent(CREATEjButton1)))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(networkjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(enterpriseTypejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterprisenAMEjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CREATEjButton1)
                    .addComponent(backjButton2))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void networkjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkjComboBox1ActionPerformed
        
    }//GEN-LAST:event_networkjComboBox1ActionPerformed

    private void enterpriseTypejComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseTypejComboBox1ActionPerformed
        
        
    }//GEN-LAST:event_enterpriseTypejComboBox1ActionPerformed

    private void CREATEjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEjButton1ActionPerformed
        Network network = (Network) networkjComboBox1.getSelectedItem();
        
        String name = enterprisenAMEjTextField1.getText();
        
        if(enterprisenAMEjTextField1.getText().isEmpty()==true || enterprisenAMEjTextField1.getText().startsWith(" ")) {
            JOptionPane.showMessageDialog(null, "Please enter valid text in enterprise name field");
            return;
        }
        
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) enterpriseTypejComboBox1.getSelectedItem();
        
        for (Network n : system.getNetworkList()){
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                if (e.getEnterpriseType().getValue().equalsIgnoreCase(type.getValue())){
                    if (type.getValue().equalsIgnoreCase(type.WareHouse.getValue())) {
                        System.out.println(e.getName());
                        JOptionPane.showMessageDialog(null, "Warehouse enterprise exists in the Network !!! Cannot create duplicate Enterprise !!!");
                        return;
                    } else if (type.getValue().equalsIgnoreCase(type.PHSenterprise.getValue())) {
                        System.out.println(e.getName());
                        JOptionPane.showMessageDialog(null, "PHS enterprise exists in the Network !!! Cannot create duplicate Enterprise !!!");
                        return;
                    }
                }
            }
        }
        
        for (Network n2 : system.getNetworkList()){
            for (Enterprise e2 : n2.getEnterpriseDirectory().getEnterpriseList()){
                if (e2.getName().equalsIgnoreCase(name)){
                    JOptionPane.showMessageDialog(null, "Same name enterprise exists !!! Cannot create duplicate Enterprise !!!");
                        return;
                }
            }
        }
        
        Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, type);
        populateEnterpriseTable();
        
    }//GEN-LAST:event_CREATEjButton1ActionPerformed

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CREATEjButton1;
    private javax.swing.JButton backjButton2;
    private javax.swing.JComboBox enterpriseTypejComboBox1;
    private javax.swing.JTable enterprisejTable1;
    private javax.swing.JTextField enterprisenAMEjTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox networkjComboBox1;
    // End of variables declaration//GEN-END:variables
}
